# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# See "https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html"
# 24 is 1.13-pre, 25 is 1.13.2, 26 is 1.14.2, 27 is 1.14.3, 28 is 1.14.4, 29 is 1.15, 30 is 1.15.1, 31 is 1.15.2
loaderVersion="[32,)" #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/beerik94/starwormlighting/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="starwormlighting" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory
# A display name for the mod
displayName="Star Worm Lighting" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://github.com/beerik94/starwormlighting/blob/mc1.15/update.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/beerik94/starwormlighting" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="starwormlighting.png" #optional
# A text field displayed in the mod UI
credits="Beerik and AlaharranHonor" #optional
# A text field displayed in the mod UI
authors="Beerik and AlaharranHonor" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Star Worm Lighting fixes the need for torches that o so clutter your beautiful designs!
'''